name: Docker Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"  # Run every day at 10:00 UTC for nightly tag
  push:
    tags:
      - 'v*'  # Push events to matching v*, i.e. v1, v1.0, v1.0.0 tags
    branches:
      - main
      - develop

jobs:
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        platform: [linux/amd64, linux/arm64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Docker Build Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/{{ cookiecutter.author_name|lower }}/{{ cookiecutter.__package_slug }}
            # docker.io/{{ cookiecutter.author_name|lower }}/{{ cookiecutter.__package_slug }}  # Uncomment for Docker Hub
          tags: |
            {% raw %}type=schedule,pattern=nightly{% endraw %}
            {% raw %}type=ref,event=branch{% endraw %}
            {% raw %}type=semver,pattern={{version}}{% endraw %}
            {% raw %}type=semver,pattern={{major}}.{{minor}}{% endraw %}
            {% raw %}type=semver,pattern={{major}}{% endraw %}
            {% raw %}type=sha{% endraw %}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      # Uncomment for Docker Hub
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: '{% raw %}${{ secrets.DOCKERHUB_USERNAME }}{% endraw %}'
      #     password: '{% raw %}${{ secrets.DOCKERHUB_TOKEN }}{% endraw %}'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: '{% raw %}${{ github.repository_owner }}{% endraw %}'
          password: '{% raw %}${{ secrets.GH_PAT }}{% endraw %}'

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: '{% raw %}${{ steps.meta.outputs.tags }}{% endraw %}'
          labels: '{% raw %}${{ steps.meta.outputs.labels }}{% endraw %}'
          platforms: linux/amd64,linux/arm64
